# Generated by Django 5.1 on 2024-08-16 02:22

from django.db import migrations


def crear_importancias(apps, sechema_editor):
    Importancia = apps.get_model('actividades', 'Importancia')
    Importancia.objects.get_or_create(titulo='Baja')
    Importancia.objects.get_or_create(titulo='Media')
    Importancia.objects.get_or_create(titulo='Alta')

def crear_estados(apps, sechema_editor):
    Estado = apps.get_model('actividades', 'Estado')
    Estado.objects.get_or_create(titulo='Creada')
    Estado.objects.get_or_create(titulo='En progreso')
    Estado.objects.get_or_create(titulo='Terminada')
    Estado.objects.get_or_create(titulo='Cancelada')

class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_rename_fecha_límite_actividad_fecha_limite'),
    ]

    operations = [
        migrations.RunPython(crear_importancias),
        migrations.RunPython(crear_estados),
    ]
