# Generated by Django 4.2.6 on 2023-11-01 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=32, verbose_name='título')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha actualización')),
            ],
            options={
                'verbose_name': 'Etiqueta de estado',
                'verbose_name_plural': 'Etiquetas de estado',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Importancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=32, verbose_name='título')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha actualización')),
            ],
            options={
                'verbose_name': 'Etiqueta de importancia',
                'verbose_name_plural': 'Etiquetas de importancia',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=256, verbose_name='título')),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('fecha_inicio', models.DateField(verbose_name='fecha inicio')),
                ('fecha_limite', models.DateField(verbose_name='fecha límite')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha actualización')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.estado')),
                ('importancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.importancia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
